// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envelopeAo.proto

package red_proto_envelope

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发送红包
type RedEnvelopeSendRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	EnvelopeType         uint32         `protobuf:"varint,2,opt,name=envelope_type,json=envelopeType,proto3" json:"envelope_type,omitempty"`
	UserName             string         `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId               uint64         `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Blessing             string         `protobuf:"bytes,5,opt,name=blessing,proto3" json:"blessing,omitempty"`
	Amount               uint64         `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Quantity             uint32         `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RedEnvelopeSendRequest) Reset()         { *m = RedEnvelopeSendRequest{} }
func (m *RedEnvelopeSendRequest) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeSendRequest) ProtoMessage()    {}
func (*RedEnvelopeSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{0}
}

func (m *RedEnvelopeSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeSendRequest.Unmarshal(m, b)
}
func (m *RedEnvelopeSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeSendRequest.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeSendRequest.Merge(m, src)
}
func (m *RedEnvelopeSendRequest) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeSendRequest.Size(m)
}
func (m *RedEnvelopeSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeSendRequest proto.InternalMessageInfo

func (m *RedEnvelopeSendRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *RedEnvelopeSendRequest) GetEnvelopeType() uint32 {
	if m != nil {
		return m.EnvelopeType
	}
	return 0
}

func (m *RedEnvelopeSendRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RedEnvelopeSendRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RedEnvelopeSendRequest) GetBlessing() string {
	if m != nil {
		return m.Blessing
	}
	return ""
}

func (m *RedEnvelopeSendRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RedEnvelopeSendRequest) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type RedEnvelopeSendResponse struct {
	RspHeader            *ResponseHeader `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	EnvelopeGoods        *EnvelopeGoods  `protobuf:"bytes,2,opt,name=envelope_goods,json=envelopeGoods,proto3" json:"envelope_goods,omitempty"`
	Link                 string          `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RedEnvelopeSendResponse) Reset()         { *m = RedEnvelopeSendResponse{} }
func (m *RedEnvelopeSendResponse) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeSendResponse) ProtoMessage()    {}
func (*RedEnvelopeSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{1}
}

func (m *RedEnvelopeSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeSendResponse.Unmarshal(m, b)
}
func (m *RedEnvelopeSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeSendResponse.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeSendResponse.Merge(m, src)
}
func (m *RedEnvelopeSendResponse) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeSendResponse.Size(m)
}
func (m *RedEnvelopeSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeSendResponse proto.InternalMessageInfo

func (m *RedEnvelopeSendResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *RedEnvelopeSendResponse) GetEnvelopeGoods() *EnvelopeGoods {
	if m != nil {
		return m.EnvelopeGoods
	}
	return nil
}

func (m *RedEnvelopeSendResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

// 收红包
type RedEnvelopeReceiveRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	EnvelopeNo           string         `protobuf:"bytes,2,opt,name=envelope_no,json=envelopeNo,proto3" json:"envelope_no,omitempty"`
	UserName             string         `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId               uint64         `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNo            string         `protobuf:"bytes,5,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RedEnvelopeReceiveRequest) Reset()         { *m = RedEnvelopeReceiveRequest{} }
func (m *RedEnvelopeReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeReceiveRequest) ProtoMessage()    {}
func (*RedEnvelopeReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{2}
}

func (m *RedEnvelopeReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeReceiveRequest.Unmarshal(m, b)
}
func (m *RedEnvelopeReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeReceiveRequest.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeReceiveRequest.Merge(m, src)
}
func (m *RedEnvelopeReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeReceiveRequest.Size(m)
}
func (m *RedEnvelopeReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeReceiveRequest proto.InternalMessageInfo

func (m *RedEnvelopeReceiveRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *RedEnvelopeReceiveRequest) GetEnvelopeNo() string {
	if m != nil {
		return m.EnvelopeNo
	}
	return ""
}

func (m *RedEnvelopeReceiveRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RedEnvelopeReceiveRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RedEnvelopeReceiveRequest) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

type RedEnvelopeReceiveResponse struct {
	RspHeader            *ResponseHeader  `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	RedEnvelopeItem      *RedEnvelopeItem `protobuf:"bytes,2,opt,name=red_envelope_item,json=redEnvelopeItem,proto3" json:"red_envelope_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RedEnvelopeReceiveResponse) Reset()         { *m = RedEnvelopeReceiveResponse{} }
func (m *RedEnvelopeReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeReceiveResponse) ProtoMessage()    {}
func (*RedEnvelopeReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{3}
}

func (m *RedEnvelopeReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeReceiveResponse.Unmarshal(m, b)
}
func (m *RedEnvelopeReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeReceiveResponse.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeReceiveResponse.Merge(m, src)
}
func (m *RedEnvelopeReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeReceiveResponse.Size(m)
}
func (m *RedEnvelopeReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeReceiveResponse proto.InternalMessageInfo

func (m *RedEnvelopeReceiveResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *RedEnvelopeReceiveResponse) GetRedEnvelopeItem() *RedEnvelopeItem {
	if m != nil {
		return m.RedEnvelopeItem
	}
	return nil
}

// 退款红包
type RedEnvelopeRefundRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	EnvelopeNo           string         `protobuf:"bytes,2,opt,name=envelope_no,json=envelopeNo,proto3" json:"envelope_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RedEnvelopeRefundRequest) Reset()         { *m = RedEnvelopeRefundRequest{} }
func (m *RedEnvelopeRefundRequest) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeRefundRequest) ProtoMessage()    {}
func (*RedEnvelopeRefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{4}
}

func (m *RedEnvelopeRefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeRefundRequest.Unmarshal(m, b)
}
func (m *RedEnvelopeRefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeRefundRequest.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeRefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeRefundRequest.Merge(m, src)
}
func (m *RedEnvelopeRefundRequest) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeRefundRequest.Size(m)
}
func (m *RedEnvelopeRefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeRefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeRefundRequest proto.InternalMessageInfo

func (m *RedEnvelopeRefundRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *RedEnvelopeRefundRequest) GetEnvelopeNo() string {
	if m != nil {
		return m.EnvelopeNo
	}
	return ""
}

type RedEnvelopeRefundResponse struct {
	RspHeader            *ResponseHeader `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	EnvelopeGoods        *EnvelopeGoods  `protobuf:"bytes,2,opt,name=envelope_goods,json=envelopeGoods,proto3" json:"envelope_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RedEnvelopeRefundResponse) Reset()         { *m = RedEnvelopeRefundResponse{} }
func (m *RedEnvelopeRefundResponse) String() string { return proto.CompactTextString(m) }
func (*RedEnvelopeRefundResponse) ProtoMessage()    {}
func (*RedEnvelopeRefundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{5}
}

func (m *RedEnvelopeRefundResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedEnvelopeRefundResponse.Unmarshal(m, b)
}
func (m *RedEnvelopeRefundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedEnvelopeRefundResponse.Marshal(b, m, deterministic)
}
func (m *RedEnvelopeRefundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedEnvelopeRefundResponse.Merge(m, src)
}
func (m *RedEnvelopeRefundResponse) XXX_Size() int {
	return xxx_messageInfo_RedEnvelopeRefundResponse.Size(m)
}
func (m *RedEnvelopeRefundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedEnvelopeRefundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedEnvelopeRefundResponse proto.InternalMessageInfo

func (m *RedEnvelopeRefundResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *RedEnvelopeRefundResponse) GetEnvelopeGoods() *EnvelopeGoods {
	if m != nil {
		return m.EnvelopeGoods
	}
	return nil
}

// 查询红包商品
type GetRedEnvelopRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	EnvelopeNo           string         `protobuf:"bytes,2,opt,name=envelope_no,json=envelopeNo,proto3" json:"envelope_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRedEnvelopRequest) Reset()         { *m = GetRedEnvelopRequest{} }
func (m *GetRedEnvelopRequest) String() string { return proto.CompactTextString(m) }
func (*GetRedEnvelopRequest) ProtoMessage()    {}
func (*GetRedEnvelopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{6}
}

func (m *GetRedEnvelopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedEnvelopRequest.Unmarshal(m, b)
}
func (m *GetRedEnvelopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedEnvelopRequest.Marshal(b, m, deterministic)
}
func (m *GetRedEnvelopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedEnvelopRequest.Merge(m, src)
}
func (m *GetRedEnvelopRequest) XXX_Size() int {
	return xxx_messageInfo_GetRedEnvelopRequest.Size(m)
}
func (m *GetRedEnvelopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedEnvelopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedEnvelopRequest proto.InternalMessageInfo

func (m *GetRedEnvelopRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *GetRedEnvelopRequest) GetEnvelopeNo() string {
	if m != nil {
		return m.EnvelopeNo
	}
	return ""
}

type GetRedEnvelopeResponse struct {
	RspHeader            *ResponseHeader `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	EnvelopeGoods        *EnvelopeGoods  `protobuf:"bytes,2,opt,name=envelope_goods,json=envelopeGoods,proto3" json:"envelope_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRedEnvelopeResponse) Reset()         { *m = GetRedEnvelopeResponse{} }
func (m *GetRedEnvelopeResponse) String() string { return proto.CompactTextString(m) }
func (*GetRedEnvelopeResponse) ProtoMessage()    {}
func (*GetRedEnvelopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{7}
}

func (m *GetRedEnvelopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedEnvelopeResponse.Unmarshal(m, b)
}
func (m *GetRedEnvelopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedEnvelopeResponse.Marshal(b, m, deterministic)
}
func (m *GetRedEnvelopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedEnvelopeResponse.Merge(m, src)
}
func (m *GetRedEnvelopeResponse) XXX_Size() int {
	return xxx_messageInfo_GetRedEnvelopeResponse.Size(m)
}
func (m *GetRedEnvelopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedEnvelopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedEnvelopeResponse proto.InternalMessageInfo

func (m *GetRedEnvelopeResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *GetRedEnvelopeResponse) GetEnvelopeGoods() *EnvelopeGoods {
	if m != nil {
		return m.EnvelopeGoods
	}
	return nil
}

// 查询用户发送的红包商品
type ListSentRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserId               uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint64         `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint64         `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListSentRequest) Reset()         { *m = ListSentRequest{} }
func (m *ListSentRequest) String() string { return proto.CompactTextString(m) }
func (*ListSentRequest) ProtoMessage()    {}
func (*ListSentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{8}
}

func (m *ListSentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSentRequest.Unmarshal(m, b)
}
func (m *ListSentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSentRequest.Marshal(b, m, deterministic)
}
func (m *ListSentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSentRequest.Merge(m, src)
}
func (m *ListSentRequest) XXX_Size() int {
	return xxx_messageInfo_ListSentRequest.Size(m)
}
func (m *ListSentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSentRequest proto.InternalMessageInfo

func (m *ListSentRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *ListSentRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListSentRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSentRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListSentResponse struct {
	RspHeader            *ResponseHeader  `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	TotalPage            uint64           `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	EnvelopeGoods        []*EnvelopeGoods `protobuf:"bytes,3,rep,name=envelope_goods,json=envelopeGoods,proto3" json:"envelope_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListSentResponse) Reset()         { *m = ListSentResponse{} }
func (m *ListSentResponse) String() string { return proto.CompactTextString(m) }
func (*ListSentResponse) ProtoMessage()    {}
func (*ListSentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{9}
}

func (m *ListSentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSentResponse.Unmarshal(m, b)
}
func (m *ListSentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSentResponse.Marshal(b, m, deterministic)
}
func (m *ListSentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSentResponse.Merge(m, src)
}
func (m *ListSentResponse) XXX_Size() int {
	return xxx_messageInfo_ListSentResponse.Size(m)
}
func (m *ListSentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSentResponse proto.InternalMessageInfo

func (m *ListSentResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *ListSentResponse) GetTotalPage() uint64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *ListSentResponse) GetEnvelopeGoods() []*EnvelopeGoods {
	if m != nil {
		return m.EnvelopeGoods
	}
	return nil
}

// 查询用户收到的红包记录
type ListReceivedRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserId               uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint64         `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint64         `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListReceivedRequest) Reset()         { *m = ListReceivedRequest{} }
func (m *ListReceivedRequest) String() string { return proto.CompactTextString(m) }
func (*ListReceivedRequest) ProtoMessage()    {}
func (*ListReceivedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{10}
}

func (m *ListReceivedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceivedRequest.Unmarshal(m, b)
}
func (m *ListReceivedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceivedRequest.Marshal(b, m, deterministic)
}
func (m *ListReceivedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceivedRequest.Merge(m, src)
}
func (m *ListReceivedRequest) XXX_Size() int {
	return xxx_messageInfo_ListReceivedRequest.Size(m)
}
func (m *ListReceivedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceivedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceivedRequest proto.InternalMessageInfo

func (m *ListReceivedRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *ListReceivedRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListReceivedRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListReceivedRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListReceivedResponse struct {
	RspHeader            *ResponseHeader    `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	TotalPage            uint64             `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	EnvelopeItems        []*RedEnvelopeItem `protobuf:"bytes,3,rep,name=envelope_items,json=envelopeItems,proto3" json:"envelope_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListReceivedResponse) Reset()         { *m = ListReceivedResponse{} }
func (m *ListReceivedResponse) String() string { return proto.CompactTextString(m) }
func (*ListReceivedResponse) ProtoMessage()    {}
func (*ListReceivedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{11}
}

func (m *ListReceivedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceivedResponse.Unmarshal(m, b)
}
func (m *ListReceivedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceivedResponse.Marshal(b, m, deterministic)
}
func (m *ListReceivedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceivedResponse.Merge(m, src)
}
func (m *ListReceivedResponse) XXX_Size() int {
	return xxx_messageInfo_ListReceivedResponse.Size(m)
}
func (m *ListReceivedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceivedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceivedResponse proto.InternalMessageInfo

func (m *ListReceivedResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *ListReceivedResponse) GetTotalPage() uint64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *ListReceivedResponse) GetEnvelopeItems() []*RedEnvelopeItem {
	if m != nil {
		return m.EnvelopeItems
	}
	return nil
}

// 查询用户已经抢到的红包列表
type ListReceivableRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	Page                 uint64         `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint64         `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListReceivableRequest) Reset()         { *m = ListReceivableRequest{} }
func (m *ListReceivableRequest) String() string { return proto.CompactTextString(m) }
func (*ListReceivableRequest) ProtoMessage()    {}
func (*ListReceivableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{12}
}

func (m *ListReceivableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceivableRequest.Unmarshal(m, b)
}
func (m *ListReceivableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceivableRequest.Marshal(b, m, deterministic)
}
func (m *ListReceivableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceivableRequest.Merge(m, src)
}
func (m *ListReceivableRequest) XXX_Size() int {
	return xxx_messageInfo_ListReceivableRequest.Size(m)
}
func (m *ListReceivableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceivableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceivableRequest proto.InternalMessageInfo

func (m *ListReceivableRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *ListReceivableRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListReceivableRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListReceivableResponse struct {
	RspHeader            *ResponseHeader  `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	TotalPage            uint64           `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	EnvelopeGoods        []*EnvelopeGoods `protobuf:"bytes,3,rep,name=envelope_goods,json=envelopeGoods,proto3" json:"envelope_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListReceivableResponse) Reset()         { *m = ListReceivableResponse{} }
func (m *ListReceivableResponse) String() string { return proto.CompactTextString(m) }
func (*ListReceivableResponse) ProtoMessage()    {}
func (*ListReceivableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{13}
}

func (m *ListReceivableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceivableResponse.Unmarshal(m, b)
}
func (m *ListReceivableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceivableResponse.Marshal(b, m, deterministic)
}
func (m *ListReceivableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceivableResponse.Merge(m, src)
}
func (m *ListReceivableResponse) XXX_Size() int {
	return xxx_messageInfo_ListReceivableResponse.Size(m)
}
func (m *ListReceivableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceivableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceivableResponse proto.InternalMessageInfo

func (m *ListReceivableResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *ListReceivableResponse) GetTotalPage() uint64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *ListReceivableResponse) GetEnvelopeGoods() []*EnvelopeGoods {
	if m != nil {
		return m.EnvelopeGoods
	}
	return nil
}

// 查询红包商品详情
type ListItemsRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	EnvelopeNo           string         `protobuf:"bytes,2,opt,name=envelope_no,json=envelopeNo,proto3" json:"envelope_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListItemsRequest) Reset()         { *m = ListItemsRequest{} }
func (m *ListItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ListItemsRequest) ProtoMessage()    {}
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{14}
}

func (m *ListItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsRequest.Unmarshal(m, b)
}
func (m *ListItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsRequest.Marshal(b, m, deterministic)
}
func (m *ListItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsRequest.Merge(m, src)
}
func (m *ListItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ListItemsRequest.Size(m)
}
func (m *ListItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsRequest proto.InternalMessageInfo

func (m *ListItemsRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *ListItemsRequest) GetEnvelopeNo() string {
	if m != nil {
		return m.EnvelopeNo
	}
	return ""
}

type ListItemsResponse struct {
	RspHeader            *ResponseHeader    `protobuf:"bytes,1,opt,name=rsp_header,json=rspHeader,proto3" json:"rsp_header,omitempty"`
	EnvelopeItems        []*RedEnvelopeItem `protobuf:"bytes,2,rep,name=envelope_items,json=envelopeItems,proto3" json:"envelope_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListItemsResponse) Reset()         { *m = ListItemsResponse{} }
func (m *ListItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ListItemsResponse) ProtoMessage()    {}
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f780df9b430c6b7, []int{15}
}

func (m *ListItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsResponse.Unmarshal(m, b)
}
func (m *ListItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsResponse.Marshal(b, m, deterministic)
}
func (m *ListItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsResponse.Merge(m, src)
}
func (m *ListItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ListItemsResponse.Size(m)
}
func (m *ListItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsResponse proto.InternalMessageInfo

func (m *ListItemsResponse) GetRspHeader() *ResponseHeader {
	if m != nil {
		return m.RspHeader
	}
	return nil
}

func (m *ListItemsResponse) GetEnvelopeItems() []*RedEnvelopeItem {
	if m != nil {
		return m.EnvelopeItems
	}
	return nil
}

func init() {
	proto.RegisterType((*RedEnvelopeSendRequest)(nil), "red.proto.envelope.RedEnvelopeSendRequest")
	proto.RegisterType((*RedEnvelopeSendResponse)(nil), "red.proto.envelope.RedEnvelopeSendResponse")
	proto.RegisterType((*RedEnvelopeReceiveRequest)(nil), "red.proto.envelope.RedEnvelopeReceiveRequest")
	proto.RegisterType((*RedEnvelopeReceiveResponse)(nil), "red.proto.envelope.RedEnvelopeReceiveResponse")
	proto.RegisterType((*RedEnvelopeRefundRequest)(nil), "red.proto.envelope.RedEnvelopeRefundRequest")
	proto.RegisterType((*RedEnvelopeRefundResponse)(nil), "red.proto.envelope.RedEnvelopeRefundResponse")
	proto.RegisterType((*GetRedEnvelopRequest)(nil), "red.proto.envelope.GetRedEnvelopRequest")
	proto.RegisterType((*GetRedEnvelopeResponse)(nil), "red.proto.envelope.GetRedEnvelopeResponse")
	proto.RegisterType((*ListSentRequest)(nil), "red.proto.envelope.ListSentRequest")
	proto.RegisterType((*ListSentResponse)(nil), "red.proto.envelope.ListSentResponse")
	proto.RegisterType((*ListReceivedRequest)(nil), "red.proto.envelope.ListReceivedRequest")
	proto.RegisterType((*ListReceivedResponse)(nil), "red.proto.envelope.ListReceivedResponse")
	proto.RegisterType((*ListReceivableRequest)(nil), "red.proto.envelope.ListReceivableRequest")
	proto.RegisterType((*ListReceivableResponse)(nil), "red.proto.envelope.ListReceivableResponse")
	proto.RegisterType((*ListItemsRequest)(nil), "red.proto.envelope.ListItemsRequest")
	proto.RegisterType((*ListItemsResponse)(nil), "red.proto.envelope.ListItemsResponse")
}

func init() { proto.RegisterFile("envelopeAo.proto", fileDescriptor_6f780df9b430c6b7) }

var fileDescriptor_6f780df9b430c6b7 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x96, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xbb, 0x49, 0x9e, 0xa4, 0x9e, 0xbe, 0xef, 0xd3, 0x27, 0xf5, 0x63, 0x54, 0x11, 0x5c,
	0x10, 0xa1, 0xd0, 0x1c, 0xca, 0x17, 0xa0, 0x07, 0xd4, 0x16, 0xa1, 0x16, 0xb9, 0x48, 0x48, 0x48,
	0x28, 0x72, 0xe3, 0x21, 0x18, 0x62, 0xaf, 0x63, 0xaf, 0x2b, 0x05, 0x89, 0x03, 0x07, 0xbe, 0x01,
	0x07, 0xce, 0x48, 0x48, 0x9c, 0x10, 0x67, 0x0e, 0x9c, 0xf8, 0x06, 0x7c, 0x21, 0x64, 0xaf, 0xed,
	0xda, 0x89, 0x5b, 0x47, 0x95, 0x55, 0x95, 0xdb, 0xee, 0x7a, 0x66, 0xe7, 0xbf, 0xbf, 0xd9, 0x99,
	0x35, 0x2c, 0xa3, 0x7d, 0x82, 0x03, 0xe6, 0xe0, 0x0e, 0xeb, 0x38, 0x2e, 0xe3, 0x8c, 0x52, 0x17,
	0x0d, 0x31, 0xec, 0xc4, 0xdf, 0x94, 0xc5, 0x78, 0x24, 0x3e, 0x28, 0xf3, 0x3d, 0x66, 0x59, 0xcc,
	0x16, 0x33, 0xf5, 0x43, 0x05, 0x9a, 0x1a, 0x1a, 0x0f, 0x23, 0x9b, 0x23, 0xb4, 0x0d, 0x0d, 0x87,
	0x3e, 0x7a, 0x9c, 0x3e, 0x00, 0x70, 0x71, 0xd8, 0x7d, 0x85, 0xba, 0x81, 0xae, 0x4c, 0x5a, 0xa4,
	0x3d, 0xb7, 0x7d, 0xa3, 0x33, 0x19, 0xa1, 0x13, 0x39, 0xec, 0x85, 0x86, 0x9a, 0xe4, 0xe2, 0x50,
	0x0c, 0xe9, 0x06, 0x2c, 0xc4, 0x46, 0x5d, 0x3e, 0x72, 0x50, 0xae, 0xb4, 0x48, 0x7b, 0x41, 0x9b,
	0x8f, 0x17, 0x9f, 0x8e, 0x1c, 0xa4, 0xd7, 0x40, 0xf2, 0x3d, 0x74, 0xbb, 0xb6, 0x6e, 0xa1, 0x5c,
	0x6d, 0x91, 0xb6, 0xa4, 0xcd, 0x06, 0x0b, 0x07, 0xba, 0x85, 0x74, 0x0d, 0x1a, 0xe1, 0x47, 0xd3,
	0x90, 0x6b, 0x2d, 0xd2, 0xae, 0x69, 0xf5, 0x60, 0xba, 0x6f, 0x50, 0x05, 0x66, 0x8f, 0x07, 0xe8,
	0x79, 0xa6, 0xdd, 0x97, 0xff, 0x11, 0x4e, 0xf1, 0x9c, 0x36, 0xa1, 0xae, 0x5b, 0xcc, 0xb7, 0xb9,
	0x5c, 0x17, 0x3e, 0x62, 0x16, 0xf8, 0x0c, 0x7d, 0xdd, 0xe6, 0x26, 0x1f, 0xc9, 0x8d, 0x50, 0x49,
	0x32, 0x57, 0x7f, 0x10, 0x58, 0x9b, 0xe0, 0xe0, 0x39, 0xcc, 0xf6, 0x90, 0xee, 0x00, 0xb8, 0x9e,
	0x93, 0x05, 0xa1, 0xe6, 0x83, 0x10, 0x1e, 0x09, 0x09, 0xcf, 0x89, 0x48, 0xec, 0x41, 0x92, 0x86,
	0x6e, 0x9f, 0x31, 0xc3, 0x0b, 0x51, 0x9c, 0xc1, 0x33, 0x16, 0xb1, 0x1b, 0x18, 0x6a, 0x09, 0xc2,
	0x70, 0x4a, 0x29, 0xd4, 0x06, 0xa6, 0xfd, 0x26, 0x22, 0x15, 0x8e, 0xd5, 0xdf, 0x04, 0xfe, 0x4f,
	0x89, 0xd7, 0xb0, 0x87, 0xe6, 0x09, 0x96, 0x97, 0xc7, 0xeb, 0x30, 0x97, 0xa8, 0xb7, 0x59, 0x28,
	0x5d, 0xd2, 0x20, 0x5e, 0x3a, 0x60, 0x17, 0xcc, 0xe1, 0x3a, 0x80, 0xde, 0xeb, 0x05, 0xa9, 0x09,
	0x76, 0x15, 0x59, 0x94, 0xa2, 0x95, 0x03, 0xa6, 0x7e, 0x27, 0xa0, 0xe4, 0x9d, 0xaa, 0xbc, 0xac,
	0x1c, 0xc2, 0x8a, 0x8b, 0x46, 0x37, 0x39, 0x9b, 0xc9, 0xd1, 0x8a, 0x12, 0xb3, 0x91, 0xbf, 0x53,
	0xa2, 0x66, 0x9f, 0xa3, 0xa5, 0x2d, 0xb9, 0xd9, 0x05, 0xf5, 0x1d, 0xc8, 0x19, 0xc5, 0x2f, 0xfd,
	0x32, 0xcb, 0xa9, 0x28, 0x0d, 0xea, 0xd7, 0xf1, 0x7b, 0x20, 0xe2, 0x5f, 0xc1, 0x6b, 0xac, 0x8e,
	0x60, 0x75, 0x17, 0xf9, 0xa9, 0xd8, 0x4b, 0xa4, 0xf4, 0x85, 0x40, 0x33, 0x13, 0x1b, 0xaf, 0x26,
	0xa2, 0x8f, 0x04, 0x96, 0x1e, 0x9b, 0x1e, 0x3f, 0x42, 0x9b, 0x97, 0x87, 0x27, 0x55, 0x8d, 0x95,
	0x4c, 0x35, 0x52, 0xa8, 0x39, 0x7a, 0x5f, 0x94, 0x6f, 0x4d, 0x0b, 0xc7, 0xc1, 0x9a, 0x67, 0xbe,
	0xc5, 0xa8, 0x6e, 0xc3, 0xb1, 0xfa, 0x93, 0xc0, 0xf2, 0xa9, 0xac, 0xf2, 0xc0, 0xad, 0x03, 0x70,
	0xc6, 0xf5, 0x41, 0x37, 0x54, 0x21, 0xb4, 0x49, 0xe1, 0xca, 0x93, 0x40, 0xca, 0x24, 0xd7, 0x6a,
	0xab, 0x7a, 0x21, 0xae, 0x9f, 0x08, 0xfc, 0x1b, 0x1c, 0x20, 0x6a, 0x28, 0xc6, 0x15, 0x62, 0xfb,
	0x8b, 0xc0, 0x6a, 0x56, 0xda, 0xa5, 0xf1, 0x7d, 0x94, 0xe2, 0x1b, 0xf4, 0xc1, 0x98, 0xef, 0x54,
	0x8d, 0x30, 0x21, 0x1c, 0xcc, 0x3c, 0xf5, 0x3d, 0x81, 0xff, 0x4e, 0x8f, 0xa1, 0x1f, 0x0f, 0x4a,
	0x7c, 0x8b, 0x62, 0x94, 0x95, 0x1c, 0x94, 0xd5, 0x2c, 0xca, 0xe6, 0xb8, 0x86, 0xbf, 0xf0, 0xb2,
	0xfa, 0xa2, 0xd8, 0x42, 0xae, 0x97, 0xd8, 0x23, 0x3f, 0x13, 0x58, 0x49, 0xc5, 0x2d, 0x0f, 0xdc,
	0xe4, 0x35, 0xab, 0x5c, 0xf4, 0x9a, 0x6d, 0x7f, 0xab, 0xc3, 0x42, 0xca, 0x64, 0x87, 0x51, 0x03,
	0x1a, 0xc1, 0x9f, 0xdb, 0xa1, 0xcf, 0xe9, 0x66, 0xc1, 0x86, 0xa9, 0x3f, 0x5d, 0xe5, 0xee, 0x54,
	0xb6, 0xe2, 0x48, 0xea, 0x0c, 0x7d, 0x0d, 0x8d, 0xa8, 0x40, 0xe9, 0x56, 0x81, 0x67, 0xf6, 0x57,
	0x4c, 0xe9, 0x4c, 0x6b, 0x9e, 0xc4, 0xea, 0x43, 0x5d, 0x3c, 0xe3, 0xf4, 0x5e, 0xa1, 0x6f, 0xea,
	0x6f, 0x43, 0xd9, 0x9a, 0xd2, 0x3a, 0x09, 0xf4, 0x02, 0xaa, 0xbb, 0xc8, 0x69, 0x3b, 0xcf, 0x2f,
	0xef, 0xa5, 0x56, 0x36, 0x0b, 0x2d, 0xd3, 0xe7, 0x78, 0x06, 0xb3, 0xf1, 0xa3, 0x41, 0x73, 0x73,
	0x3d, 0xf6, 0xd2, 0x29, 0x37, 0xcf, 0x37, 0x4a, 0x36, 0xee, 0xc1, 0x7c, 0xba, 0x63, 0xd2, 0xdb,
	0x67, 0xf9, 0x8d, 0xb5, 0x7b, 0xa5, 0x5d, 0x6c, 0x98, 0x04, 0x31, 0x61, 0x31, 0xdb, 0x4b, 0xe8,
	0x9d, 0xf3, 0xbd, 0x53, 0x3d, 0x2f, 0x1f, 0x54, 0x7e, 0x6b, 0x52, 0x67, 0xe8, 0x73, 0x90, 0x92,
	0xc2, 0xa3, 0x67, 0x42, 0x48, 0xf7, 0x03, 0xe5, 0x56, 0x81, 0x55, 0xbc, 0xf7, 0x71, 0x3d, 0xb4,
	0xb9, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x93, 0x48, 0x86, 0x51, 0x39, 0x0e, 0x00, 0x00,
}
