// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accountAo.proto

package red_proto_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserId               uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string         `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	AccountName          string         `protobuf:"bytes,4,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountType          uint32         `protobuf:"varint,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CurrencyCode         string         `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Amount               uint64         `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *CreateAccountRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateAccountRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *CreateAccountRequest) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *CreateAccountRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CreateAccountRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreateAccountResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	Account              *Account        `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountTransferRequest struct {
	ReqHeader            *RequestHeader   `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	AccountTransfer      *AccountTransfer `protobuf:"bytes,2,opt,name=account_transfer,json=accountTransfer,proto3" json:"account_transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountTransferRequest) Reset()         { *m = AccountTransferRequest{} }
func (m *AccountTransferRequest) String() string { return proto.CompactTextString(m) }
func (*AccountTransferRequest) ProtoMessage()    {}
func (*AccountTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{2}
}

func (m *AccountTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransferRequest.Unmarshal(m, b)
}
func (m *AccountTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransferRequest.Marshal(b, m, deterministic)
}
func (m *AccountTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransferRequest.Merge(m, src)
}
func (m *AccountTransferRequest) XXX_Size() int {
	return xxx_messageInfo_AccountTransferRequest.Size(m)
}
func (m *AccountTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransferRequest proto.InternalMessageInfo

func (m *AccountTransferRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *AccountTransferRequest) GetAccountTransfer() *AccountTransfer {
	if m != nil {
		return m.AccountTransfer
	}
	return nil
}

type AccountTransferResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	TransferStatus       int32           `protobuf:"varint,2,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccountTransferResponse) Reset()         { *m = AccountTransferResponse{} }
func (m *AccountTransferResponse) String() string { return proto.CompactTextString(m) }
func (*AccountTransferResponse) ProtoMessage()    {}
func (*AccountTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{3}
}

func (m *AccountTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransferResponse.Unmarshal(m, b)
}
func (m *AccountTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransferResponse.Marshal(b, m, deterministic)
}
func (m *AccountTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransferResponse.Merge(m, src)
}
func (m *AccountTransferResponse) XXX_Size() int {
	return xxx_messageInfo_AccountTransferResponse.Size(m)
}
func (m *AccountTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransferResponse proto.InternalMessageInfo

func (m *AccountTransferResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *AccountTransferResponse) GetTransferStatus() int32 {
	if m != nil {
		return m.TransferStatus
	}
	return 0
}

type StoreValueRequest struct {
	ReqHeader            *RequestHeader   `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	AccountTransfer      *AccountTransfer `protobuf:"bytes,2,opt,name=account_transfer,json=accountTransfer,proto3" json:"account_transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoreValueRequest) Reset()         { *m = StoreValueRequest{} }
func (m *StoreValueRequest) String() string { return proto.CompactTextString(m) }
func (*StoreValueRequest) ProtoMessage()    {}
func (*StoreValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{4}
}

func (m *StoreValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueRequest.Unmarshal(m, b)
}
func (m *StoreValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueRequest.Marshal(b, m, deterministic)
}
func (m *StoreValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueRequest.Merge(m, src)
}
func (m *StoreValueRequest) XXX_Size() int {
	return xxx_messageInfo_StoreValueRequest.Size(m)
}
func (m *StoreValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueRequest proto.InternalMessageInfo

func (m *StoreValueRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *StoreValueRequest) GetAccountTransfer() *AccountTransfer {
	if m != nil {
		return m.AccountTransfer
	}
	return nil
}

type StoreValueResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	TransferStatus       int32           `protobuf:"varint,2,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StoreValueResponse) Reset()         { *m = StoreValueResponse{} }
func (m *StoreValueResponse) String() string { return proto.CompactTextString(m) }
func (*StoreValueResponse) ProtoMessage()    {}
func (*StoreValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{5}
}

func (m *StoreValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueResponse.Unmarshal(m, b)
}
func (m *StoreValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueResponse.Marshal(b, m, deterministic)
}
func (m *StoreValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueResponse.Merge(m, src)
}
func (m *StoreValueResponse) XXX_Size() int {
	return xxx_messageInfo_StoreValueResponse.Size(m)
}
func (m *StoreValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueResponse proto.InternalMessageInfo

func (m *StoreValueResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *StoreValueResponse) GetTransferStatus() int32 {
	if m != nil {
		return m.TransferStatus
	}
	return 0
}

type GetEnvelopeAccountByUserIdRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserId               uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetEnvelopeAccountByUserIdRequest) Reset()         { *m = GetEnvelopeAccountByUserIdRequest{} }
func (m *GetEnvelopeAccountByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetEnvelopeAccountByUserIdRequest) ProtoMessage()    {}
func (*GetEnvelopeAccountByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{6}
}

func (m *GetEnvelopeAccountByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdRequest.Unmarshal(m, b)
}
func (m *GetEnvelopeAccountByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *GetEnvelopeAccountByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEnvelopeAccountByUserIdRequest.Merge(m, src)
}
func (m *GetEnvelopeAccountByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdRequest.Size(m)
}
func (m *GetEnvelopeAccountByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEnvelopeAccountByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEnvelopeAccountByUserIdRequest proto.InternalMessageInfo

func (m *GetEnvelopeAccountByUserIdRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *GetEnvelopeAccountByUserIdRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetEnvelopeAccountByUserIdResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	Accounts             []*Account      `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetEnvelopeAccountByUserIdResponse) Reset()         { *m = GetEnvelopeAccountByUserIdResponse{} }
func (m *GetEnvelopeAccountByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetEnvelopeAccountByUserIdResponse) ProtoMessage()    {}
func (*GetEnvelopeAccountByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{7}
}

func (m *GetEnvelopeAccountByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdResponse.Unmarshal(m, b)
}
func (m *GetEnvelopeAccountByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetEnvelopeAccountByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEnvelopeAccountByUserIdResponse.Merge(m, src)
}
func (m *GetEnvelopeAccountByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetEnvelopeAccountByUserIdResponse.Size(m)
}
func (m *GetEnvelopeAccountByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEnvelopeAccountByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEnvelopeAccountByUserIdResponse proto.InternalMessageInfo

func (m *GetEnvelopeAccountByUserIdResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *GetEnvelopeAccountByUserIdResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetAccountRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	AccountNo            string         `protobuf:"bytes,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{8}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *GetAccountRequest) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

type GetAccountResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	Account              *Account        `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3ea59a651a8e75, []int{9}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "red.proto.account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "red.proto.account.CreateAccountResponse")
	proto.RegisterType((*AccountTransferRequest)(nil), "red.proto.account.AccountTransferRequest")
	proto.RegisterType((*AccountTransferResponse)(nil), "red.proto.account.AccountTransferResponse")
	proto.RegisterType((*StoreValueRequest)(nil), "red.proto.account.StoreValueRequest")
	proto.RegisterType((*StoreValueResponse)(nil), "red.proto.account.StoreValueResponse")
	proto.RegisterType((*GetEnvelopeAccountByUserIdRequest)(nil), "red.proto.account.GetEnvelopeAccountByUserIdRequest")
	proto.RegisterType((*GetEnvelopeAccountByUserIdResponse)(nil), "red.proto.account.GetEnvelopeAccountByUserIdResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "red.proto.account.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "red.proto.account.GetAccountResponse")
}

func init() { proto.RegisterFile("accountAo.proto", fileDescriptor_8a3ea59a651a8e75) }

var fileDescriptor_8a3ea59a651a8e75 = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xee, 0xb6, 0x69, 0x1e, 0x93, 0x84, 0x36, 0x2b, 0x68, 0x2d, 0x23, 0xa4, 0x64, 0x01, 0x35,
	0x70, 0xc8, 0x21, 0x14, 0xae, 0x28, 0xad, 0x50, 0xe1, 0x00, 0x07, 0xa7, 0x70, 0xe1, 0x10, 0x19,
	0x7b, 0x10, 0x95, 0x1a, 0xaf, 0xb3, 0x5e, 0x57, 0xca, 0x81, 0x03, 0x17, 0x2e, 0x48, 0x08, 0xfe,
	0x01, 0x12, 0x42, 0xe2, 0x67, 0xa2, 0xec, 0xc3, 0x4d, 0x6b, 0x97, 0x14, 0x29, 0xa8, 0xbd, 0x79,
	0xbf, 0xfd, 0xe6, 0xf5, 0x79, 0x66, 0x16, 0x36, 0xfc, 0x20, 0xe0, 0x69, 0x24, 0x07, 0xbc, 0x17,
	0x0b, 0x2e, 0x39, 0x6d, 0x09, 0x0c, 0xf5, 0x67, 0xcf, 0x5c, 0xb9, 0x8d, 0x80, 0x8f, 0xc7, 0x3c,
	0xd2, 0xa8, 0xdb, 0x34, 0xb0, 0x3e, 0xb2, 0x6f, 0xab, 0x70, 0x73, 0x5f, 0xa0, 0x2f, 0x71, 0xa0,
	0x71, 0x0f, 0x27, 0x29, 0x26, 0x92, 0x3e, 0x05, 0x10, 0x38, 0x19, 0x7d, 0x40, 0x3f, 0x44, 0xe1,
	0x90, 0x36, 0xe9, 0xd6, 0xfb, 0xed, 0x5e, 0xce, 0x7b, 0xcf, 0xf0, 0x9f, 0x2b, 0x9e, 0x57, 0x13,
	0x38, 0xd1, 0x9f, 0x74, 0x1b, 0x2a, 0x69, 0x82, 0x62, 0x74, 0x14, 0x3a, 0xab, 0x6d, 0xd2, 0x2d,
	0x79, 0xe5, 0xd9, 0xf1, 0x45, 0x48, 0x6f, 0x43, 0x4d, 0x5d, 0x44, 0xfe, 0x18, 0x9d, 0xb5, 0x36,
	0xe9, 0xd6, 0xbc, 0xea, 0x0c, 0x78, 0xe5, 0x8f, 0x91, 0x76, 0xa0, 0x61, 0x3c, 0xeb, 0xfb, 0x92,
	0xba, 0xaf, 0x1b, 0xec, 0x3c, 0x45, 0x4e, 0x63, 0x74, 0xd6, 0xdb, 0xa4, 0xdb, 0xcc, 0x28, 0x87,
	0xd3, 0x18, 0xe9, 0x5d, 0x68, 0x06, 0xa9, 0x10, 0x18, 0x05, 0xd3, 0x51, 0xc0, 0x43, 0x74, 0xca,
	0xca, 0x4d, 0xc3, 0x82, 0xfb, 0x3c, 0x44, 0xba, 0x05, 0x65, 0x7f, 0x3c, 0x33, 0x71, 0x2a, 0x3a,
	0x3f, 0x7d, 0x62, 0xdf, 0x09, 0xdc, 0x3a, 0x27, 0x49, 0x12, 0xf3, 0x28, 0x41, 0xba, 0x07, 0x75,
	0x81, 0x49, 0x7c, 0x56, 0x94, 0x4e, 0xa1, 0x28, 0xda, 0xc2, 0xa8, 0x02, 0x33, 0x2b, 0x23, 0xcb,
	0x2e, 0x54, 0x0c, 0x4b, 0xc9, 0x52, 0xef, 0xbb, 0x05, 0xf6, 0x36, 0xb0, 0xa5, 0xb2, 0xdf, 0x04,
	0xb6, 0x0c, 0x78, 0x28, 0xfc, 0x28, 0x79, 0x8f, 0x62, 0x69, 0x3f, 0xea, 0x25, 0x6c, 0x66, 0x7a,
	0x1a, 0xdf, 0x26, 0x35, 0x76, 0x71, 0x6a, 0x59, 0x16, 0xb6, 0x03, 0x2d, 0xc0, 0x3e, 0x13, 0xd8,
	0xce, 0xa5, 0xba, 0x44, 0x01, 0x77, 0x60, 0xc3, 0xa6, 0x39, 0x4a, 0xa4, 0x2f, 0xd3, 0x44, 0x65,
	0xbb, 0xee, 0xdd, 0xb0, 0xf0, 0x50, 0xa1, 0xec, 0x27, 0x81, 0xd6, 0x50, 0x72, 0x81, 0x6f, 0xfc,
	0xe3, 0x14, 0xaf, 0xab, 0x5c, 0x9f, 0x08, 0xd0, 0xf9, 0x2c, 0xaf, 0x42, 0xa9, 0x8f, 0xd0, 0x39,
	0x40, 0xf9, 0x2c, 0x3a, 0xc1, 0x63, 0x1e, 0xdb, 0xae, 0xdf, 0x9b, 0xbe, 0x56, 0xf3, 0xfa, 0xdf,
	0x17, 0x02, 0xfb, 0x41, 0x80, 0xfd, 0x2d, 0xfe, 0x12, 0x25, 0x79, 0x02, 0x55, 0xc3, 0x9a, 0x69,
	0xb1, 0xb6, 0x60, 0xfc, 0x32, 0x2e, 0x4b, 0xa0, 0x75, 0x80, 0x72, 0xd9, 0x2b, 0xf2, 0x0e, 0x40,
	0xb6, 0xec, 0xb8, 0x12, 0xa5, 0xe6, 0xd5, 0xec, 0xaa, 0xe3, 0xec, 0x2b, 0x01, 0x3a, 0x1f, 0xf5,
	0xaa, 0xb7, 0x50, 0xff, 0x57, 0x09, 0x36, 0x07, 0xf6, 0xc1, 0x19, 0xa2, 0x38, 0x39, 0x0a, 0x90,
	0x86, 0xd0, 0x3c, 0xb3, 0x2d, 0xe9, 0x4e, 0x81, 0xab, 0xa2, 0x27, 0xc6, 0xed, 0x2e, 0x26, 0xea,
	0x02, 0xd8, 0x0a, 0x0d, 0xa0, 0x6a, 0x47, 0x86, 0x3e, 0xb8, 0xc4, 0x9c, 0x99, 0x10, 0x0f, 0x2f,
	0x43, 0xcd, 0x82, 0xbc, 0x05, 0x38, 0x1d, 0x45, 0x7a, 0xaf, 0xc0, 0x36, 0xb7, 0x4f, 0xdc, 0xfb,
	0x0b, 0x58, 0x99, 0xf3, 0x2f, 0x04, 0xdc, 0x8b, 0xbb, 0x9c, 0xee, 0x16, 0xf8, 0x59, 0x38, 0x94,
	0xee, 0xe3, 0x7f, 0xb4, 0x9a, 0x2f, 0xf5, 0xb4, 0xb5, 0x0a, 0x4b, 0xcd, 0xf5, 0x7b, 0x61, 0xa9,
	0xf9, 0xfe, 0x64, 0x2b, 0xef, 0xca, 0x8a, 0xf3, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0x34, 0x7f, 0x63, 0x9e, 0x08, 0x00, 0x00,
}
