// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package red_proto_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	AccountNo            string   `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountType          uint32   `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	UserId               uint64   `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateAt             uint64   `protobuf:"varint,9,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *Account) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *Account) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *Account) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Account) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Account) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Account) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Account) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdateAt() uint64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type TradeParticipator struct {
	AccountNo            string   `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	AccountType          int32    `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeParticipator) Reset()         { *m = TradeParticipator{} }
func (m *TradeParticipator) String() string { return proto.CompactTextString(m) }
func (*TradeParticipator) ProtoMessage()    {}
func (*TradeParticipator) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *TradeParticipator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeParticipator.Unmarshal(m, b)
}
func (m *TradeParticipator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeParticipator.Marshal(b, m, deterministic)
}
func (m *TradeParticipator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeParticipator.Merge(m, src)
}
func (m *TradeParticipator) XXX_Size() int {
	return xxx_messageInfo_TradeParticipator.Size(m)
}
func (m *TradeParticipator) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeParticipator.DiscardUnknown(m)
}

var xxx_messageInfo_TradeParticipator proto.InternalMessageInfo

func (m *TradeParticipator) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *TradeParticipator) GetAccountType() int32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *TradeParticipator) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TradeParticipator) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type AccountTransfer struct {
	TradeBody            *TradeParticipator `protobuf:"bytes,1,opt,name=trade_body,json=tradeBody,proto3" json:"trade_body,omitempty"`
	TradeTarget          *TradeParticipator `protobuf:"bytes,2,opt,name=trade_target,json=tradeTarget,proto3" json:"trade_target,omitempty"`
	Amount               uint64             `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ChangeType           int32              `protobuf:"varint,4,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	ChangeFlag           int32              `protobuf:"varint,5,opt,name=change_flag,json=changeFlag,proto3" json:"change_flag,omitempty"`
	Desc                 string             `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountTransfer) Reset()         { *m = AccountTransfer{} }
func (m *AccountTransfer) String() string { return proto.CompactTextString(m) }
func (*AccountTransfer) ProtoMessage()    {}
func (*AccountTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AccountTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountTransfer.Unmarshal(m, b)
}
func (m *AccountTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountTransfer.Marshal(b, m, deterministic)
}
func (m *AccountTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountTransfer.Merge(m, src)
}
func (m *AccountTransfer) XXX_Size() int {
	return xxx_messageInfo_AccountTransfer.Size(m)
}
func (m *AccountTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_AccountTransfer proto.InternalMessageInfo

func (m *AccountTransfer) GetTradeBody() *TradeParticipator {
	if m != nil {
		return m.TradeBody
	}
	return nil
}

func (m *AccountTransfer) GetTradeTarget() *TradeParticipator {
	if m != nil {
		return m.TradeTarget
	}
	return nil
}

func (m *AccountTransfer) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountTransfer) GetChangeType() int32 {
	if m != nil {
		return m.ChangeType
	}
	return 0
}

func (m *AccountTransfer) GetChangeFlag() int32 {
	if m != nil {
		return m.ChangeFlag
	}
	return 0
}

func (m *AccountTransfer) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "red.proto.account.Account")
	proto.RegisterType((*TradeParticipator)(nil), "red.proto.account.TradeParticipator")
	proto.RegisterType((*AccountTransfer)(nil), "red.proto.account.AccountTransfer")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x95, 0xc1, 0x18, 0x3c, 0x06, 0x55, 0xec, 0xa1, 0xb5, 0x54, 0x55, 0xa5, 0xb4, 0x07, 0x4e,
	0x3e, 0xb4, 0x5f, 0x40, 0x91, 0x12, 0xe5, 0x12, 0x45, 0xc8, 0x77, 0x6b, 0xd8, 0x1d, 0x1c, 0x24,
	0xf0, 0x5a, 0xeb, 0xf5, 0xc1, 0xdf, 0x10, 0xe5, 0x13, 0xf2, 0xaf, 0xd1, 0x8e, 0x0d, 0x01, 0xa1,
	0x48, 0xc9, 0x6d, 0xe7, 0xcd, 0x9b, 0xd9, 0x79, 0xef, 0xc1, 0x04, 0xa5, 0xd4, 0x75, 0x61, 0x93,
	0xd2, 0x68, 0xab, 0xc5, 0xd4, 0x90, 0x6a, 0x9f, 0x49, 0xd7, 0x98, 0xbf, 0xf4, 0x60, 0xb8, 0x6c,
	0xdf, 0xe2, 0x07, 0x40, 0x07, 0x67, 0x85, 0x8e, 0xbd, 0x99, 0xb7, 0x08, 0xd7, 0x61, 0x87, 0xdc,
	0x6b, 0xf1, 0x0b, 0xc6, 0xa7, 0x36, 0x1e, 0x28, 0xee, 0x31, 0x21, 0x3a, 0x12, 0xf0, 0x40, 0xe7,
	0x14, 0xdb, 0x94, 0x14, 0xf7, 0x67, 0xde, 0x62, 0x72, 0xa2, 0xa4, 0x4d, 0x49, 0xe2, 0x37, 0x4c,
	0x64, 0x6d, 0x0c, 0x15, 0xb2, 0xc9, 0xa4, 0x56, 0x14, 0xfb, 0xbc, 0x66, 0x7c, 0x04, 0x57, 0x5a,
	0x91, 0xf8, 0x06, 0xc3, 0xba, 0x22, 0x93, 0xed, 0x54, 0x3c, 0x98, 0x79, 0x0b, 0x7f, 0x1d, 0xb8,
	0xf2, 0x4e, 0x89, 0xef, 0x10, 0x72, 0x83, 0x0f, 0x08, 0x78, 0x72, 0xe4, 0x00, 0xfe, 0xfd, 0x2b,
	0x04, 0x95, 0x45, 0x5b, 0x57, 0xf1, 0x90, 0xff, 0xed, 0x2a, 0xa7, 0x4b, 0x1a, 0x42, 0x4b, 0x2a,
	0x43, 0x1b, 0x8f, 0x78, 0x61, 0xd8, 0x21, 0x4b, 0xcb, 0x3b, 0x4b, 0x85, 0x96, 0x5c, 0x37, 0xe4,
	0xee, 0xa8, 0x05, 0x96, 0x76, 0xfe, 0xe4, 0xc1, 0x34, 0x35, 0xa8, 0xe8, 0x01, 0x8d, 0xdd, 0xc9,
	0x5d, 0x89, 0x56, 0x9b, 0x4f, 0x38, 0xc5, 0x36, 0x38, 0xa7, 0x06, 0x97, 0x36, 0x9c, 0x29, 0xec,
	0xbf, 0xaf, 0xd0, 0xbf, 0x54, 0x38, 0x7f, 0xee, 0xc1, 0x97, 0x2e, 0xad, 0xd4, 0x60, 0x51, 0x6d,
	0xc9, 0x88, 0x15, 0x80, 0x75, 0x07, 0x66, 0x1b, 0xad, 0x1a, 0xbe, 0x25, 0xfa, 0xfb, 0x27, 0xb9,
	0x4a, 0x3a, 0xb9, 0x52, 0xb1, 0x0e, 0x79, 0xee, 0xbf, 0x56, 0x8d, 0xb8, 0x85, 0x71, 0xbb, 0xc4,
	0xa2, 0xc9, 0xc9, 0xf2, 0xc5, 0x1f, 0x5d, 0x13, 0xf1, 0x64, 0xca, 0x83, 0x2e, 0x03, 0x3c, 0x38,
	0xe2, 0x51, 0x56, 0x5b, 0x89, 0x9f, 0x10, 0xc9, 0x47, 0x2c, 0x72, 0x6a, 0x1d, 0xf1, 0xd9, 0x11,
	0x68, 0x21, 0x36, 0xe4, 0x8d, 0xb0, 0xdd, 0x63, 0xce, 0xb1, 0x9f, 0x08, 0x37, 0x7b, 0xcc, 0x85,
	0x00, 0x5f, 0x51, 0x25, 0xbb, 0xd4, 0xf9, 0xbd, 0x09, 0xf8, 0xb6, 0x7f, 0xaf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x19, 0x08, 0xb5, 0x64, 0xe8, 0x02, 0x00, 0x00,
}
