// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userAo.proto

package red_proto_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ffa33e647e71b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type CreateUserRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserName             string         `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName             string         `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ffa33e647e71b, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type CreateUserResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	UserId               uint64          `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ffa33e647e71b, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *CreateUserResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserRequest struct {
	ReqHeader            *RequestHeader `protobuf:"bytes,1,opt,name=req_header,json=reqHeader,proto3" json:"req_header,omitempty"`
	UserId               uint64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ffa33e647e71b, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetReqHeader() *RequestHeader {
	if m != nil {
		return m.ReqHeader
	}
	return nil
}

func (m *GetUserRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResponse struct {
	RespHeader           *ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	User                 *User           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba0ffa33e647e71b, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetRespHeader() *ResponseHeader {
	if m != nil {
		return m.RespHeader
	}
	return nil
}

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "red.proto.user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "red.proto.user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "red.proto.user.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "red.proto.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "red.proto.user.GetUserResponse")
}

func init() { proto.RegisterFile("userAo.proto", fileDescriptor_ba0ffa33e647e71b) }

var fileDescriptor_ba0ffa33e647e71b = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xa5, 0x92, 0x56, 0x86, 0x5a, 0xe3, 0xc6, 0xc4, 0x06, 0xa3, 0x56, 0x4e, 0x9c, 0x38,
	0xe0, 0xd5, 0xc4, 0x18, 0x0f, 0x6a, 0x62, 0x3c, 0x60, 0x38, 0x78, 0x6a, 0x10, 0x26, 0x4a, 0x0c,
	0x2c, 0xec, 0x52, 0x4f, 0xbe, 0x81, 0xaf, 0xe3, 0x03, 0x9a, 0xd9, 0x45, 0x85, 0x92, 0x7a, 0x69,
	0x6f, 0xcb, 0xfc, 0xff, 0xf0, 0x7f, 0x33, 0x19, 0x18, 0x2f, 0x24, 0x8a, 0x2b, 0xee, 0x97, 0x82,
	0xd7, 0x9c, 0x4d, 0x04, 0xa6, 0xfa, 0xe9, 0x53, 0xdd, 0x19, 0x27, 0x3c, 0xcf, 0x79, 0xa1, 0x4b,
	0xee, 0x13, 0x98, 0x91, 0x44, 0xc1, 0x0e, 0x61, 0x44, 0xea, 0x3c, 0x4b, 0xa7, 0xc6, 0xcc, 0xf0,
	0xcc, 0x70, 0x48, 0x9f, 0x77, 0x29, 0x3b, 0x02, 0x4b, 0x09, 0x45, 0x9c, 0xe3, 0x74, 0x30, 0x33,
	0x3c, 0x2b, 0xdc, 0xa1, 0xc2, 0x43, 0x9c, 0x23, 0x89, 0x45, 0x96, 0xbc, 0x69, 0x71, 0x5b, 0x8b,
	0x54, 0x20, 0xd1, 0xfd, 0x34, 0x60, 0xff, 0x5a, 0x60, 0x5c, 0x23, 0x25, 0x84, 0x58, 0x2d, 0x50,
	0xd6, 0xec, 0x02, 0x40, 0x60, 0x35, 0x7f, 0xc5, 0x38, 0x45, 0xa1, 0xb2, 0xec, 0xe0, 0xd8, 0xef,
	0x32, 0xfa, 0x8d, 0xf9, 0x56, 0x99, 0x42, 0x4b, 0x60, 0xa5, 0x9f, 0x6b, 0xd0, 0x14, 0xc0, 0xda,
	0x30, 0xb2, 0xe4, 0x85, 0x44, 0x76, 0x09, 0xb6, 0x40, 0x59, 0x76, 0x71, 0x4e, 0xfa, 0x38, 0xda,
	0xde, 0xf0, 0x00, 0xb5, 0x34, 0x40, 0xad, 0xbd, 0x0d, 0xda, 0x7b, 0x73, 0x5f, 0x60, 0x72, 0x83,
	0xf5, 0xe6, 0x26, 0x5f, 0x19, 0xf4, 0x01, 0x7b, 0xbf, 0x41, 0x9b, 0x9a, 0xca, 0x03, 0x93, 0x2c,
	0x2a, 0xc9, 0x0e, 0x0e, 0x96, 0x3b, 0x55, 0x98, 0x72, 0x04, 0x5f, 0x06, 0xec, 0x46, 0xea, 0xdc,
	0x1e, 0x51, 0xbc, 0x67, 0x09, 0xb2, 0x08, 0xe0, 0x6f, 0xd1, 0xec, 0x6c, 0xb9, 0xb7, 0x77, 0x11,
	0x8e, 0xfb, 0x9f, 0x45, 0x23, 0xba, 0x5b, 0xec, 0x1e, 0x46, 0xcd, 0x98, 0xac, 0x37, 0x49, 0x77,
	0xd1, 0xce, 0xe9, 0x4a, 0xfd, 0xe7, 0x6f, 0xcf, 0x43, 0xa5, 0x9e, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0xa8, 0x0e, 0x5e, 0x2b, 0x03, 0x00, 0x00,
}
